repos:
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.4.0
  hooks:
  - id: detect-secrets
    args: ["--baseline", ".secrets.baseline"]
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: ["--profile", "black", "--force-single-line-imports"]
- repo: https://github.com/myint/autoflake
  rev: v2.0.1
  hooks:
  - id: autoflake
    args: ["--recursive", "--remove-all-unused-imports", "--remove-unused-variables", "--in-place"]
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.0.0-alpha.4
  hooks:
    - id: prettier
      types_or: [css, javascript, html]
