site_name: eSimMon
site_url: https://esimmon.readthedocs.io
theme: readthedocs
markdown_extensions:
  - attr_list
  - pymdownx.snippets
  - md_in_html
nav:
  - 'index.md'
  - User Guide:
    - Ingesting Data: 'user-guide/ingest.md'
    - Accessing the Dashboard: 'user-guide/access.md'
    - Navigating the Dashboard: 'user-guide/navigation.md'
    - Demo: 'user-guide/demo.md'
  - Developer Guide:
    - Getting Started: 'developer-guide/dev_start.md'
    - Ansible: 'developer-guide/ansible.md'
    - Girder: 'developer-guide/girder.md'
    - FastAPI: 'developer-guide/fastapi.md'
    - Ingest/Watch: 'developer-guide/watch.md'
    - Client: 'developer-guide/client.md'
    - Ingest Schema: 'developer-guide/schema.md'
