version: "3.0"
services:
  watch:
    image: kitware/esimmon-cli
    build:
      context: ../../
      dockerfile: devops/docker/ingest/Dockerfile
    command: "watch -i 60 -v 60"
    env_file:
      - watch.env
    entrypoint: ["/wait-for-it.sh", "girder:8080", "-t", "30", "--", "/usr/local/bin/adash"]
