version: "3.0"
services:
  ansible:
    image: kitware/esimmon-ansible:0.1.0
    depends_on:
      - 'girder'
    build:
      context: ../../
      dockerfile: devops/docker/ansible/Dockerfile
    environment:
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_HOST: ${EMAIL_HOST}
    volumes:
      - ../:/devops
